movieWallet/Movies/urls.py
from django.conf.urls import url
from Movies import api
from rest_framework.urlpatterns import format_suffix_patterns
from .views import (
    Detail_movie,
    Play_movie,
    Favorite,
    Watched,
    )

app_name='Movies'

urlpatterns = [
    #movies/<movie_id>
    url(r'^(?P<movie_id>\d+)/$', Detail_movie, name="detail_movie"),
    #movies/<movie_id>/play/
    url(r'^(?P<movie_id>\d+)/play/$', Play_movie, name="play"),
    #movies/<movie_id>/watched/
    url(r'^(?P<movie_id>\d+)/watched/$', Favorite, name="favorite"),
    #movies/<movie_id>/watched/
    url(r'^(?P<movie_id>\d+)/watched/stay=True$', Watched, name="watched"),
    #movies/api/name=<name>
    url(r'^api/name=(?P<name>[A-Z,a-z," ",""]+|)?&y=(?P<year>[0-9]+|)$',api.API_res,name="api"),
]

movieWallet/movieWallet/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Movies import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name="index"),
    #movies/
    url(r'^movies/',include('Movies.urls')),

    #register/
    url(r'^register/$', views.register, name='register'),
    #logged_in/
    url(r'^logged_in/$', views.logged_in, name='logged_in'),
    #logged_out/
    url(r'^logged_out/$', views.log_out, name='log_out'),
    #search/ 
    url(r'^search/$', views.search_movie, name='search'),
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieWallet/Movies/models.py
from __future__ import unicode_literals
from django.db import models
import shelve

# Create Movie database class to hold all the movie data.
class Movie(models.Model):
    Name=models.CharField(max_length=300)
    Year=models.CharField(max_length=5)
    Plot=models.CharField(max_length=1500)
    Genre=models.CharField(max_length=250)
    Imdb_rating=models.FloatField(default=0.0)
    Plot_outline=models.CharField(max_length=1000,default=None)
    Director=models.CharField(max_length=50,default=None)
    Poster=models.FileField(default='default.jpg')
    Path=models.CharField(max_length=100)
    Watched=models.BooleanField(default=False)
    trailer=models.CharField(max_length=150,default=None,null=True,blank=True)

    def __str__(self):
        return self.Name

movieWallet/Movies/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from .models import Movie
from bs4 import BeautifulSoup
import threading
import urllib
import os
import re

# View inside the website
# define to get youTube link by the movie name.
def get_youtube_link(movie):
    # Create query using urllib function with movie name.
    query = urllib.quote_plus(movie.Name)

    # Create f variable that uses urllib to open YouTube URL plus the query name.
    f = urllib.urlopen('https://www.youtube.com/results?search_query='+query+'+trailer').read()
    
    # Using BeautifulSoup to extract data from the URL using lxml parser. 
    soup=BeautifulSoup(f,'lxml')

    # Find all the matches data and print them.
    item = soup.find_all('ol',{'class':'item-section'})
    for itm in item:
        a = item[0].find_all('a',{'class':'yt-uix-sessionlink'})[0]    
    a = re.findall('=(.*)',a.get('href'))
    print (a)

    # Send the movie trailer in its database and save it.
    link= 'http://www.youtube.com/embed/'+a[0]
    movie.trailer=link
    movie.save()

# define index which return request.
def index(request):

    # if the user try to store or retrieve data,
    # get all objects in Movie database and return main.html.
    if 'user' in request.session:
        movies=Movie.objects.all()
        return render(request,'main.html',{'movies':movies})    
    return render(request,'login.html')

# define log in which return request.
def logged_in(request):

    # When the user login and their data is authenticate get all movie objects
    # and return to the main.html page.
    if 'user' in request.session and request.user.is_authenticated:
        movies=Movie.objects.all()
        return render(request,'main.html',{'movies':movies})

    # Get the user username and password.    
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']

        # If user isn't exist show error message.
        if not User.objects.filter(username=username).exists():
            return render(request,'login.html',{'error_message':'Please Register First'})
        
        # If the user login, and their data correct, get the all movie objects and get the user to the main.html,
        # or else show error message.    
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                request.session['user']=username
                movies=Movie.objects.all()
                return render(request, 'main.html', {'movies':movies})
            else:
                return render(request,'login.html',{'error_message':'Your Account Has Been Suspended'})

        # return to the login page if the user's data is not right.        
        return render(request,'login.html',{'error_message':'Wrong Credentials'})
    return render(request,'login.html')

# define ability to register for the user
def register(request):

    # get username, password, repetition password, and email from the user.
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        rep_password=request.POST['rep_password']
        e_mail=request.POST['email']

        # if user"s email, username, and password exist show error message or else
        # set the user data and save it to the system.
        if User.objects.filter(email=e_mail).exists():
            return render(request,'register.html',{'error_message':'E-mail already registered'})
        elif User.objects.filter(username=username).exists():
            return render(request,'register.html',{'error_message':'Username not available'})
        elif(password!=rep_password):
            return render(request,'register.html',{'error_message':'Passwords Dont match'})
        else:
            user=User(username=username,email=e_mail)
            user.set_password(password)
            user.save()
            user=authenticate(username=username,password=password)
            login(request,user)
            request.session['user']=username
            movies=Movie.objects.all()
            return render(request,'main.html',{'movies':movies})
    return render(request,'register.html')

# define ability to log out for the user
def log_out(request):

    # request logout function and redirect to the login page.
    if 'user' in request.session:
        del request.session['user']
        logout(request)
        return redirect('logged_in')

# define detail movie.
def Detail_movie(request,movie_id):

    # if the user isn't authenticated direct the user to the login page
    if not request.user.is_authenticated:
        return redirect('logged_in')

    # Create a thread that print the get_youtube_link method.     
    threadobj= threading.Thread(target=get_youtube_link,args=[])
    movie=get_object_or_404(Movie,id=movie_id)
    print (movie.trailer)
    if not movie.trailer:
        try:
            get_youtube_link(movie)
        except:
            pass
    return render(request,'details.html', {'movie':movie})

# define search movie.
def search_movie(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            if not request.POST['search']:
                return redirect('logged_in')
            # Get all matches movie from the search input from the user    
            if '-w' in request.POST['search']:
                Q=re.findall('(.*)\s+-w',request.POST['search'])

                # if not match, filter by the unwatched movie else
                # get the name, year, and genre of the movie. 
                if not Q:
                    movies=Movie.objects.filter(Watched=False)
                    return render(request,'main.html',{'movies':movies})
                else:
                    Q=Q[0]
                    list1=Movie.objects.filter(Name__contains=Q,Watched=False)
                    list2=Movie.objects.filter(Year__contains=Q,Watched=False)
                    list3=Movie.objects.filter(Genre__contains=Q,Watched=False)

            # if movie found get the name, year, and genre.
            else:
                Q=request.POST['search']
                list1=Movie.objects.filter(Name__contains=Q)
                list2=Movie.objects.filter(Year__contains=Q)
                list3=Movie.objects.filter(Genre__contains=Q)

            # Set context with the list objects.
            res=list(set(list1)^set(list2)^set(list3))
            context={
                'movies':res,
            }
            return render(request,'main.html',context)
    return redirect('logged_in')

# define play movie return request and movie_id
def Play_movie(request,movie_id):

    # If requested from user is authenticated get the movie by movie id
    if request.user.is_authenticated:
        movie=get_object_or_404(Movie,id=movie_id)
        os.system('xdg-open '+'"'+movie.Path+'"')
        return render(request,'details.html',{'movie':movie})
    return redirect('logged_in')

# define favorite movies
def Favorite(request,movie_id):

    # if it's the favorite movie to watch then false else true
    if request.user.is_authenticated:
        movie=get_object_or_404(Movie,id=movie_id)
        if movie.Watched:
            movie.Watched=False
        else:
            movie.Watched=True
        movie.save()
    return redirect('logged_in')

# define marked watched and unwatched movie
def Watched(request,movie_id):

    # if the movie watched then marked as false else true
    if request.user.is_authenticated:
        movie=get_object_or_404(Movie,id=movie_id)
        if movie.Watched:
            movie.Watched=False
        else:
            movie.Watched=True
        movie.save()
        return render(request,'details.html',{'movie':movie})
    return redirect('logged_in')

movieWallet/Movies/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <!-- Page style  -->
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <title>{% block title %}Movie Wallet{% endblock %}</title>

</head>

{% load staticfiles %}
<link rel="stylesheet" href='{% static "css/Bootstrap.min.css" %}' />
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

<body>
<!-- Inside the header of the pages -->
<div class="fix">
  <nav class="navbar navbar-inverse fix" >
    <div class="container-fluid" >
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- Movie wallet logo that go to the movie list -->
        <a class="navbar-brand" href="{% url 'logged_in' %}">Movie Wallet</a>
      </div>

      <!-- Movie button option that go to the movie list -->
      <div class="collapse navbar-collapse" id="topNavBar">
        <ul class="nav navbar-nav">
          <li class="active">
            <a href="{% url 'logged_in' %}">
              &nbsp;
              Movies
            </a>
          </li>
        </ul>

        <!-- Search bar -->
        <form class="navbar-form navbar-right" action="{% url 'search' %}" method="post" role="search">
          {% csrf_token %}
          <div class="form-group">
            <input type="text" class="form-control" name="search" placeholder="Search">
          </div>
        </form>

        <!-- Logout button -->
        <ul class="nav navbar-nav navbar-right">
          <li class="">
            <a href="{% url 'log_out' %}">
            &nbsp;
            Logout
            </a>
          </li>
        </ul>
    </div>
  </div>
</nav>
</div>
{% block body %}
{% endblock %}
</body>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block script %}
{% endblock %}
</html>

movieWallet/Movies/templates/details.html
{% extends 'base.html' %}
{% block title %}{{ movie.Name }}{% endblock %}
{% block body %}
<!-- Detail page style -->
<div class="container-fluid songs-container">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-body">
                <br>
                <br>
                <!-- Display the movie name and year as title -->
                <h2>{{ movie.Name }} <small>{{ movie.Year }}</small></h2>
                <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <!-- Marked watch and unwatched movie -->
                <li role="presentation" class="active"><a href="{% url 'Movies:watched' movie.id %}">
                  {% if movie.Watched %}
                  Mark Unwatched
                  {% else %}
                  Mark Watched
                  {% endif %}
                </a></li>
                <!-- Back button to go back to the movie lists -->
                <li role="presentation" class="active"><a href="{% url 'index' %}">Back</a></li>
                </ul>
                <!-- Movie descriptions -->
                <h5><strong>Director</strong> : {{ movie.Director }}</h5>
                <h5><strong>Watched</strong> :{% if movie.Watched %}Yes{% else %}No{% endif %}</h5>
                <h5><strong>Year</strong> : {{ movie.Year }}</h5>
                <h5><strong>IMDB Rating</strong> : {{ movie.Imdb_rating }}</h5>
                <h5><strong>Genre</strong> : {{ movie.Genre }}</h5>
                <h5><strong>Plot:</strong></h5>
                <p>{{ movie.Plot }}</p>
                <!-- if the movie has a movie trailer than show the movie trailer or else show loading gif -->
                {% if movie.trailer %}
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embeded-responsive-item" src="{{movie.trailer}}" frameborder="0" allowfullscreen></iframe>
                </div>
                {% else %}
                <div style="height:480px;width:854;background-color:white;">
                    <div style="margin-top:30px">
                      img src="/static/img/no.gif"/>
                    <div>
                    </div>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

movieWallet/Movies/templates/login.html
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
	<!-- Style for the header -->
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Movie Wallet-Log In</title>

	<!-- Style for the page -->
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}"/>
</head>
<body>
<div class="form-content">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<h1 class="text-center text-bold mt-4x">Log In</h1>
				<div class="well row pt-2x pb-3x bk-light">
					<div class="col-md-8 col-md-offset-2">
						<!-- Where the error message will show -->
						{% if error_message %}
						{{ error_message }}
						{% endif %}
						<form action="{% url 'logged_in' %}" class="mt" method="post">
							{% csrf_token %}
							<!-- User login information -->
							<label for="username" class="text-uppercase text-sm">Your Username</label>
							<input type="text" placeholder="Username" class="form-control mb" name="username">
							<label for="password" class="text-uppercase text-sm">Password</label>								
							<input type="password" placeholder="Password" class="form-control mb" name="password">
						    <button class="btn btn-primary btn-block" type="submit">Login</button>
						</form>
						<br>
						<a href="{% url 'register' %}"><button class="btn btn-primary btn-block" type="submit">Sign Up</button></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Loading Scripts -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

movieWallet/Movies/templates/main.html
{% extends 'base.html' %}
{% block title %}Movie Wallet{% endblock %}
{% block body %}
<div style="width:100%;height:80px"></div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4" >
      <div class="thumbnail">
        <!-- <a href="{% url 'Movies:detail' movie.id %}">
          {% if movie.Poster %}
            <img src="{{ movie.Poster.url }}" class="img-responsive" style="max-height:440px">
          {% else %}
            <img src="../static/img/no-poster.png" class="img-responsive" style="max-height:440px">
          {% endif %}
        </a> -->
        <div class="caption">
            <!-- Movie detail information -->
            <h3>{{ movie.Name }}</h3>
            <h4>{{ movie.Year }}</h4>
            <p>{{ movie.Plot_outline }}</p>
            <!-- View Details -->
            <a href="{% url 'Movies:detail' movie.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
            <!-- Favorite Movie -->
            <a href="{% url 'Movies:favorite' movie.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
              <span class="glyphicon glyphicon-star{% if not movie.Favorite %}-empty{% endif %}"></span>
            </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

movieWallet/Movies/templates/register.html
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
	<!-- Style for the header -->
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Movie Wallet-Sign Up</title>

	<!-- Style for the page -->
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
</head>
<body>
<div class="form-content">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<h1 class="text-center text-bold mt-4x">Sign Up</h1>
				<div class="well row pt-2x pb-3x bk-light">
					<div class="col-md-8 col-md-offset-2">
						<!-- Where the error message will show -->
						{% if error_message %}
						{{ error_message }}
						{% endif %}
						<!-- Create a form from register URL which post the user data -->
						<form action="{% url 'register' %}" class="mt" method="post">
                            {% csrf_token %}
                            <!-- Where the user input their information to register -->
	  				        <label for="username" class="text-uppercase text-sm">Username</label>
							<input type="text" placeholder="Username" class="form-control mb" name="username">

							<label for="email" class="text-uppercase text-sm">E-mail</label>
							<input type="text" placeholder="E-mail" class="form-control mb" name="email">

                            <label for="password" class="text-uppercase text-sm">Password</label>
						    <input type="password" placeholder="Password" class="form-control mb" name="password">

                            <label for="password" class="text-uppercase text-sm">Password</label>							    
                            <input type="password" placeholder="Password" class="form-control mb" name="rep_password">

							<button class="btn btn-primary btn-block" type="submit">Create an account</button>
						</form>
						<br>	
						<a href="{% url 'logged_in' %}"><button class="btn btn-primary btn-block" type="submit">Sign in</button></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Loading Scripts -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>